---
- name: Configure Hostname, Domain Name, and Enable SSH on Router
  hosts: R1
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure Hostname
      become: yes
      become_method: enable
      ios_config:
        lines:
          - hostname newR1

    - name: Configure Domain Name
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip domain-name ansible.com

    - name: Generate RSA Keys for SSH
      become: yes
      become_method: enable
      ios_config:
        lines:
          - crypto key generate rsa modulus 1024

    - name: Enable SSH Version 2
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip ssh version 2

    - name: Configure VTY Lines for SSH Access
      become: yes
      become_method: enable
      ios_config:
        parents:
          - line vty 0 4
        lines:
          - login local
          - transport input ssh
- name: Configure Hostname, Domain Name, and Enable SSH on Switch
  hosts: SW1
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure Hostname
      become: yes
      become_method: enable
      ios_config:
        lines:
          - hostname newSW1

    - name: Configure Domain Name
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip domain-name ansible.com

    - name: Generate RSA Keys for SSH
      become: yes
      become_method: enable
      ios_config:
        lines:
          - crypto key generate rsa modulus 1024

    - name: Enable SSH Version 2
      become: yes
      become_method: enable
      ios_config:
        lines:
          - ip ssh version 2

    - name: Configure VTY Lines for SSH Access
      become: yes
      become_method: enable
      ios_config:
        parents:
          - line vty 0 4
        lines:
          - login local
          - transport input ssh
