---
- name: Basic_Configs
  hosts: SW1
  gather_facts: false
  connection: network_cli
 
  tasks:
  - name: Change hostname
   ios_config:
    authorize: yes
    config:
      - hostname "SW1"
      - ip domain-name "Table3.com"
  
  - name: Generate RSA key pair for SSH
    ios_config:
    authorize: yes
    config:
      - crypto key generate rsa modules 2048
  
  - name: Enable SSH on VTY lines
    ios_config:
      authorize: yes
      parents: line vty 0 4
      config:
        - transport input ssh
        - login local