---
- name: Backup Cisco router configurations
  hosts: R1
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Fetch running configuration from the Cisco device
      become: yes
      become_method: enable
      ios_command:
        authorize: yes
        commands:
          - show running-config
      register: running_config

    - name: Save the running configuration to a local file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: backups/{{ inventory_hostname }}_config_backup.txt"

- name: Backup Cisco switch configurations
  hosts: SW1
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Fetch running configuration from the Cisco device
      become: yes
      become_method: enable
      ios_command:
        authorize: yes
        commands:
          - show running-config
      register: running_config

    - name: Save the running configuration to a local file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: backups/{{ inventory_hostname }}_config_backup.txt"