---
- name: Backup Cisco router and switch configurations
  hosts: R1
  gather_facts: no
  connection: network_cli
  become: yes
  tasks:
    - name: Fetch running configuration from the Cisco device
      ios_command:
        authorize: yes
        commands:
          - show running-config
      register: running_config

    - name: Save the running configuration to a local file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/cisco-automation/{{ inventory_hostname }}_config_backup.txt"